name             'easy_dev'
maintainer       'Celine Aussourd'
maintainer_email ''
license          'all_rights'
description      'Configures developers VM'
long_description 'Configures developers VM'
version          '0.2.0'
recipe           'easy_dev', 'include recipes in the cookbook'
recipe           'easy_dev::apache_group', 'Add users to apache group'
